# Generated by Django 5.0.1 on 2024-01-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careertrack',
            fields=[
                ('Track', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('Skills', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('Emp_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('pwd', models.CharField(blank=True, max_length=16000, null=True)),
                ('Emp_designation', models.CharField(blank=True, max_length=40, null=True)),
                ('Emp_department', models.CharField(blank=True, max_length=40, null=True)),
                ('Emp_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('Emp_location', models.CharField(blank=True, max_length=40, null=True)),
                ('Emp_doj', models.DateField(blank=True, null=True)),
                ('Emp_manager', models.CharField(blank=True, max_length=40, null=True)),
                ('Emp_project', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('proficiency_level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empdetails.empdetails')),
            ],
        ),
    ]
